{
 "title": "Pure Storage FlashArray overhead analysis",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": "label_values(purefa_info, job)" },
   {
    "name": "instance",
    "label": "FlashArray",
    "query": "label_values(purefa_info{job=\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "array name",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "purefa_info{job=~\"$job\",instance=\"$instance\"}",
     "legendFormat": "{{ array_name }}"
    }
   ]
  },
  {
   "title": "used capacity delta",
   "type": "graph",
   "gridPos": { "h": 12, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n  delta(\n    purefa_array_space_used_bytes{job=~\"$job\",instance=\"$instance\"}[1d]\n  )\n)",
     "legendFormat": "1 day"
    },
    {
     "expr": "sum(\n  delta(\n    purefa_array_space_used_bytes{job=~\"$job\",instance=\"$instance\"}[1w]\n  )\n)",
     "legendFormat": "1 week"
    },
    {
     "expr": "sum(\n  delta(\n    purefa_array_space_used_bytes{job=~\"$job\",instance=\"$instance\"}[4w]\n  )\n)",
     "legendFormat": "4 weeks"
    }
   ]
  },
  {
   "title": "used system space delta",
   "type": "graph",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "delta(\n  purefa_array_space_used_bytes{job=~\"$job\",instance=\"$instance\",dimension=\"system\"}[1h]\n)",
     "legendFormat": "1h"
    },
    {
     "expr": "delta(\n  purefa_array_space_used_bytes{job=~\"$job\",instance=\"$instance\",dimension=\"system\"}[3h]\n)",
     "legendFormat": "3h"
    },
    {
     "expr": "delta(\n  purefa_array_space_used_bytes{job=~\"$job\",instance=\"$instance\",dimension=\"system\"}[6h]\n)",
     "legendFormat": "6h"
    }
   ]
  },
  {
   "title": "array capacity usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefa_array_space_used_bytes{job=~\"$job\",instance=\"$instance\"})\n/\nsum(purefa_array_space_capacity_bytes{job=~\"$job\",instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "array capacity system usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefa_array_space_used_bytes{job=~\"$job\",instance=\"$instance\",dimension=\"system\"})\n/\nsum(purefa_array_space_capacity_bytes{job=~\"$job\",instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "data reduction ratio",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefa_array_space_datareduction_ratio{job=~\"$job\",instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "capacity usage distribution",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n  purefa_array_space_used_bytes{job=~\"$job\",instance=\"$instance\"}\n) by (dimension)",
     "legendFormat": "{{ dimension }}"
    },
    {
     "expr": "sum(purefa_array_space_capacity_bytes{job=~\"$job\",instance=\"$instance\"})\n-\nsum(\n  purefa_array_space_used_bytes{job=~\"$job\",instance=\"$instance\"}\n)",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "used system space total",
   "type": "graph",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "purefa_array_space_used_bytes{job=~\"$job\",instance=\"$instance\",dimension=\"system\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "average iops",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefa_array_performance_iops{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "{{ dimension }}"
    }
   ]
  },
  {
   "title": "average throughput",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefa_array_performance_throughput_bytes{job=~\"$job\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "capacity usage %",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(purefa_array_space_used_bytes{job=~\"$job\",instance=\"$instance\"})/sum(purefa_array_space_capacity_bytes{job=~\"$job\",instance=\"$instance\"})",
     "legendFormat": "Percent usage"
    }
   ]
  },
  {
   "title": "average IO latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(purefa_array_performance_latency_usec{job=~\"$job\",instance=~\"$instance\"}) / 1000"
    }
   ]
  }
 ]
}