{
 "title": "Pure Storage FlashBlade filesystem detail",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": "label_values(purefb_info, job)" },
   {
    "name": "instance",
    "label": "FlashBlade",
    "query": "label_values(purefb_info{job=\"$job\"}, instance)"
   },
   {
    "name": "filesystem",
    "label": "File System",
    "query": "label_values(purefb_filesystems_space_bytes{job=\"$job\",instance=\"$instance\"}, name)"
   }
  ]
 },
 "panels": [
  {
   "title": "array name",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "purefb_info{job=~\"$job\",instance=\"$instance\"}",
     "legendFormat": "{{ array_name }}"
    }
   ]
  },
  {
   "title": "capacity usage distribution",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "purefb_filesystems_space_bytes{job=~\"$job\",instance=~\"$instance\",name=\"$filesystem\",dimension=\"virtual\"}\n",
     "legendFormat": "{{ dimension }}"
    },
    {
     "expr": "purefb_filesystems_space_bytes{job=~\"$job\",instance=~\"$instance\",name=\"$filesystem\",dimension=\"total_physical\"}",
     "legendFormat": "{{ dimension }}"
    },
    {
     "expr": "purefb_filesystems_space_bytes{job=~\"$job\",instance=~\"$instance\",name=\"$filesystem\",dimension=\"unique\"}",
     "legendFormat": "{{ dimension }}"
    },
    {
     "expr": "purefb_filesystems_space_bytes{job=~\"$job\",instance=~\"$instance\",name=\"$filesystem\",dimension=\"snapshots\"}",
     "legendFormat": "{{ dimension }}"
    },
    {
     "expr": "purefb_filesystems_space_bytes{job=~\"$job\",instance=~\"$instance\",name=\"$filesystem\",dimension=\"provisioned\"}",
     "legendFormat": "{{ dimension }}"
    }
   ]
  },
  {
   "title": "average file system iops",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefb_filesystem_performance_iops{job=~\"$job\",instance=\"$instance\",name=\"$filesystem\"})"
    }
   ]
  },
  {
   "title": "data reduction ratio",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefb_filesystems_data_reduction{job=~\"$job\",instance=\"$instance\",name=\"$filesystem\"})"
    }
   ]
  },
  {
   "title": "file system capacity usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefb_filesystems_space_bytes{job=~\"$job\",instance=~\"$instance\",dimension=\"virtual\",name=\"$filesystem\"})\n/\nsum(purefb_filesystems_space_bytes{job=~\"$job\",instance=~\"$instance\",dimension=\"provisioned\",name=\"$filesystem\"})"
    }
   ]
  },
  {
   "title": "average file system latency",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 13, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(purefb_filesystem_performance_latency_usec{job=~\"$job\",instance=\"$instance\",name=\"$filesystem\"}) / 1000"
    }
   ]
  },
  {
   "title": "iops read ratio",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(purefb_filesystem_performance_iops{job=~\"$job\",instance=~\"$instance\",name=\"$filesystem\",dimension=\"read\"})\n/\nsum(purefb_filesystem_performance_iops{job=~\"$job\",instance=~\"$instance\",name=\"$filesystem\"})"
    }
   ]
  },
  {
   "title": "iops write ratio",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(purefb_filesystem_performance_iops{job=~\"$job\",instance=~\"$instance\",name=\"$filesystem\",dimension=\"write\"})\n/\nsum(purefb_filesystem_performance_iops{job=~\"$job\",instance=~\"$instance\",name=\"$filesystem\"})"
    }
   ]
  },
  {
   "title": "volume capacity",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "purefb_filesystems_space_bytes{job=~\"$job\",instance=~\"$instance\",dimension=\"virtual\",name=\"$filesystem\"}"
    }
   ]
  },
  {
   "title": "average file system throughput",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefb_filesystem_performance_throughput_bytes{instance=\"$instance\",job=\"$job\",name=\"$filesystem\"})"
    }
   ]
  },
  {
   "title": "file systems iops",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(purefb_filesystem_performance_iops{job=~\"$job\",instance=\"$instance\",name=\"$filesystem\",dimension=\"read\"}\n)",
     "legendFormat": "{{filesystem}} read "
    },
    {
     "expr": "sum(\n  purefb_filesystem_performance_iops{job=~\"$job\",instance=\"$instance\",name=\"$filesystem\",dimension=\"write\"}\n)",
     "legendFormat": "{{filesystem}} write "
    }
   ]
  },
  {
   "title": "file system latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(\n  purefb_filesystem_performance_latency_usec{job=~\"$job\",instance=\"$instance\",name=\"$filesystem\",dimension=\"read\"}\n) / 1000",
     "legendFormat": "{{ volume}} read "
    },
    {
     "expr": "sum(\n  purefb_filesystem_performance_latency_usec{job=~\"$job\",instance=\"$instance\",name=\"$filesystem\",dimension=\"write\"}\n) / 1000",
     "legendFormat": "{{ volume}} write "
    }
   ]
  },
  {
   "title": "volume throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(\n  purefb_filesystem_performance_throughput_bytes{instance=\"$instance\",job=\"$job\",name=\"$filesystem\",dimension=\"read\"}\n)",
     "legendFormat": "{{ volume}} read "
    },
    {
     "expr": "sum(\n  purefb_filesystem_performance_throughput_bytes{instance=\"$instance\",job=\"$job\",name=\"$filesystem\",dimension=\"write\"}\n)",
     "legendFormat": "{{ volume}} write "
    }
   ]
  }
 ]
}