{
 "title": "Pure Storage FlashArray system detail",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": "label_values(purefa_info, job)" },
   {
    "name": "instance",
    "label": "FlashArray",
    "query": "label_values(purefa_info{job=\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "array name",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "purefa_info{job=~\"$job\",instance=\"$instance\"}",
     "legendFormat": "{{ array_name }}"
    }
   ]
  },
  {
   "title": "firmware",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "purefa_info{job=~\"$job\",instance=\"$instance\"}",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "system events",
   "type": "table",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(purefa_alerts_total{job=~\"$job\",instance=~\"$instance\"}) by(severity)",
     "legendFormat": "{{ severity }}"
    }
   ]
  },
  {
   "title": "array capacity usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(purefa_space_used_bytes{job=~\"$job\",instance=\"$instance\"})\n/\nsum(purefa_space_capacity_bytes{job=~\"$job\",instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "average iops",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "sum(purefa_performance_iops{job=~\"$job\",instance=\"$instance\"})",
     "legendFormat": "{{ dimension }}"
    }
   ]
  },
  {
   "title": "average latency",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "avg(purefa_performance_latency_usec{job=~\"$job\",instance=\"$instance\"}) / 1000"
    }
   ]
  },
  {
   "title": "average throughput",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "targets": [
    {
     "expr": "sum(purefa_performance_throughput_bytes{job=~\"$job\",instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "location",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "purefa_info{job=~\"$job\",instance=\"$instance\"}",
     "legendFormat": "{{ site}}"
    }
   ]
  },
  {
   "title": "hardware health",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(\n  count(purefa_hardware_component_health{job=~\"$job\",instance=~\"$instance\"})\n  -\n  sum(purefa_hardware_component_health{job=~\"$job\",instance=~\"$instance\"})\n)\n+\n(\n  count(purefa_hardware_chassis_health{job=~\"$job\",instance=~\"$instance\"})\n  -\n  sum(purefa_hardware_chassis_health{job=~\"$job\",instance=~\"$instance\"})\n)\n+\n(\n  count(purefa_hardware_controller_health{job=~\"$job\",instance=~\"$instance\"})\n  -\n  sum(purefa_hardware_controller_health{job=~\"$job\",instance=~\"$instance\"})\n)"
    }
   ]
  },
  {
   "title": "capacity usage distribution",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n  purefa_space_used_bytes{job=~\"$job\",instance=\"$instance\"}\n) by (dimension)",
     "legendFormat": "{{ dimension }}"
    },
    {
     "expr": "sum(purefa_space_capacity_bytes{job=~\"$job\",instance=\"$instance\"})\n-\nsum(\n  purefa_space_used_bytes{job=~\"$job\",instance=\"$instance\"}\n)",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "average mirror latency",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "purefa_mirror_write_latency_usec{job=~\"$job\",instance=\"$instance\"} / 1000"
    }
   ]
  },
  {
   "title": "mirrored write (ActiveCluster)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 3, "y": 5 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "purefa_mirror_write_bytes{job=~\"$job\",instance=\"$instance\"}",
     "legendFormat": "throughput"
    },
    {
     "expr": "purefa_mirror_write_iops{job=~\"$job\",instance=\"$instance\"}",
     "legendFormat": "iops"
    }
   ]
  },
  {
   "title": "data reduction ratio",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(purefa_space_datareduction_ratio{job=~\"$job\",instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "4 week capacity delta",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n  delta(\n    purefa_space_used_bytes{job=~\"$job\",instance=\"$instance\"}[4w]\n  )\n)"
    }
   ]
  },
  {
   "title": "io ratio",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 7 },
   "targets": [
    {
     "expr": "sum(purefa_performance_iops{job=~\"$job\",instance=~\"$instance\",dimension=\"write\"})\n/\nsum(purefa_performance_iops{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "write"
    },
    {
     "expr": "sum(purefa_performance_iops{job=~\"$job\",instance=~\"$instance\",dimension=\"read\"})\n/\nsum(purefa_performance_iops{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "read"
    }
   ]
  },
  { "title": "array performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "array iops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(\n  purefa_performance_iops{job=~\"$job\",instance=\"$instance\",dimension=\"read\"}\n)",
     "legendFormat": "read "
    },
    {
     "expr": "sum(\n  purefa_performance_iops{job=~\"$job\",instance=\"$instance\",dimension=\"write\"}\n)",
     "legendFormat": "write "
    }
   ]
  },
  {
   "title": "array latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(\n  purefa_performance_latency_usec{job=~\"$job\",instance=\"$instance\",dimension=\"read\"}\n) / 1000",
     "legendFormat": "read "
    },
    {
     "expr": "sum(\n  purefa_performance_latency_usec{job=~\"$job\",instance=\"$instance\",dimension=\"write\"}\n) / 1000",
     "legendFormat": "write "
    }
   ]
  },
  {
   "title": "array throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(\n  purefa_performance_throughput_bytes{job=~\"$job\",instance=\"$instance\",dimension=\"read\"}\n)",
     "legendFormat": "read "
    },
    {
     "expr": "sum(\n  purefa_performance_throughput_bytes{job=~\"$job\",instance=\"$instance\",dimension=\"write\"}\n)",
     "legendFormat": "write "
    }
   ]
  },
  { "title": "top talker volumes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "top talker volumes by iops",
   "type": "table",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(\n  purefa_volume_iops{job=~\"$job\",instance=\"$instance\"}\n) by (volume)",
     "legendFormat": "{{ volume }}"
    }
   ]
  },
  {
   "title": "top talker volumes by latency",
   "type": "table",
   "gridPos": { "h": 15, "w": 8, "x": 8, "y": 34 },
   "targets": [
    {
     "expr": "avg(\n  purefa_volume_latency_usec{job=~\"$job\",instance=\"$instance\",volume!~\"CV_.*\"}\n) by (volume) / 1000",
     "legendFormat": "{{ volume }}"
    }
   ]
  },
  {
   "title": "top talker volumes by throughput",
   "type": "table",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 34 },
   "targets": [
    {
     "expr": "sum(\n  purefa_volume_throughput_bytes{job=~\"$job\",instance=\"$instance\",volume!~\"CV_.*\"}\n) by (volume)",
     "legendFormat": "{{ volume }}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  purefa_host_iops{job=~\"$job\",instance=\"$instance\"}\n) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}