{
 "title": "Pure Storage FlashBlade system hardware health",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": "label_values(purefb_info, job)" },
   {
    "name": "instance",
    "label": "FlashBlade",
    "query": "label_values(purefb_info{job=\"$job\"}, instance)"
   },
   {
    "name": "controller",
    "label": "Controller",
    "query": "label_values(purefb_hardware_controller_health{instance=~\"$instance\"},controller)"
   },
   {
    "name": "fabricmodule",
    "label": "Fabric Module",
    "query": "label_values(purefb_hw_status{instance=~\"$instance\",type=\"fm\"},name)"
   }
  ]
 },
 "panels": [
  {
   "title": "array name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "purefb_info{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{ array_name }}"
    }
   ]
  },
  {
   "title": "firmware version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "purefb_info{job=~\"$job\",instance=\"$instance\"}",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "system events",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "sum(purefb_open_events_total{job=~\"$job\",instance=~\"$instance\"}) by(severity)",
     "legendFormat": "{{ severity }}"
    }
   ]
  },
  {
   "title": "capacity usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefb_array_space_bytes{job=~\"$job\",instance=~\"$instance\",dimension=\"total_physical\"})\n/\nsum(purefb_array_capacity_bytes{job=~\"$job\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "average iops",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefb_array_performance_iops{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "{{ dimension }}"
    }
   ]
  },
  {
   "title": "average IO latency",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(purefb_array_performance_latency_usec{job=~\"$job\",instance=~\"$instance\"}) / 1000"
    }
   ]
  },
  {
   "title": "data reduction",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefb_array_space_data_reduction{job=~\"$job\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "average throughput",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefb_array_performance_throughput_bytes{job=~\"$job\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "chassis health",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "purefb_hardware_chassis_health{job=\"$job\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "flash blades",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(purefb_hw_status{job=\"$job\",instance=\"$instance\",type=\"fb\"})\n-\nsum(purefb_hw_status{job=\"$job\",instance=\"$instance\",type=\"fb\"})"
    }
   ]
  },
  {
   "title": "failed flash blades",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "purefb_hw_status{job=~\"$job\",instance=~\"$instance\",type=\"fb\"} != 1",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "failed power supplies",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "purefb_hw_status{job=~\"$job\",instance=~\"$instance\",type=\"pwr\"} != 1",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "power supply",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(purefb_hw_status{job=\"$job\",instance=\"$instance\",type=\"pwr\"})\n-\nsum(purefb_hw_status{job=\"$job\",instance=\"$instance\",type=\"pwr\"})"
    }
   ]
  },
  { "title": "Fabric Module $fabricmodule", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }, "repeat": "fabricmodule" },
  {
   "title": "fabric module health",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "purefb_hw_status{job=\"$job\",instance=\"$instance\",name=~\"$fabricmodule\"}"
    }
   ]
  },
  {
   "title": "ethernet ports",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(purefb_hardware_fmcomponent_health{job=\"$job\",instance=\"$instance\",fabricmodule=~\"$fabricmodule\",type=\"eth\"})\n-\nsum(purefb_hardware_fmcomponent_health{job=\"$job\",instance=\"$instance\",fabricmodule=~\"$fabricmodule\",type=\"eth\"})"
    }
   ]
  },
  {
   "title": "failed ethernet ports",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "purefb_hardware_fmcomponent_health{job=~\"$job\",instance=~\"$instance\",type=\"eth\",fabricmodule=~\"$fabricmodule\"} == 0",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "failed management ports",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "purefb_hardware_fmcomponent_health{job=~\"$job\",instance=~\"$instance\",type=\"mgmt_port\",fabricmodule=~\"$fabricmodule\"} == 0",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "failed fans",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 13 },
   "targets": [
    {
     "expr": "purefb_hardware_fmcomponent_health{job=~\"$job\",instance=~\"$instance\",type=\"fan\",fabricmodule=~\"$fabricmodule\"} == 0",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "management ports",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(purefb_hardware_fmcomponent_health{job=\"$job\",instance=\"$instance\",fabricmodule=~\"$fabricmodule\",type=\"mgmt_port\"})\n-\nsum(purefb_hardware_fmcomponent_health{job=\"$job\",instance=\"$instance\",fabricmodule=~\"$fabricmodule\",type=\"mgmt_port\"})"
    }
   ]
  },
  {
   "title": "fans",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(purefb_hardware_fmcomponent_health{job=\"$job\",instance=\"$instance\",fabricmodule=~\"$fabricmodule\",type=\"fan\"})\n-\nsum(purefb_hardware_fmcomponent_health{job=\"$job\",instance=\"$instance\",fabricmodule=~\"$fabricmodule\",type=\"fan\"})"
    }
   ]
  }
 ]
}