{
 "title": "Pure Storage FlashBlade system detail",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": "label_values(purefb_info, job)" },
   {
    "name": "instance",
    "label": "FlashBlade",
    "query": "label_values(purefb_info{job=\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "array name",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "purefb_info{job=~\"$job\",instance=\"$instance\"}",
     "legendFormat": "{{ array_name }}"
    }
   ]
  },
  {
   "title": "firmware",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "purefb_info{job=~\"$job\",instance=\"$instance\"}",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "system events",
   "type": "table",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(purefb_open_events_total{job=~\"$job\",instance=~\"$instance\"}) by(severity)",
     "legendFormat": "{{ severity }}"
    }
   ]
  },
  {
   "title": "array capacity usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(purefb_space_tot_physical_bytes{job=~\"$job\",instance=\"$instance\"})\n/\nsum(purefb_space_tot_capacity_bytes{job=~\"$job\",instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "average iops",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "sum(purefb_perf_rd_ops{job=~\"$job\",instance=\"$instance\"} + purefb_perf_wr_ops{job=~\"$job\",instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "average latency",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sum(purefb_perf_wr_latency_usec{job=~\"$job\",instance=\"$instance\"} + purefb_perf_rd_latency_usec{job=~\"$job\",instance=\"$instance\"}) / 1000"
    }
   ]
  },
  {
   "title": "average throughput",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "targets": [
    {
     "expr": "sum(purefb_perf_wr_bps{job=~\"$job\",instance=\"$instance\"} + purefb_perf_rd_bps{job=~\"$job\",instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "location",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "purefb_info{job=~\"$job\",instance=\"$instance\"}",
     "legendFormat": "{{ site}}"
    }
   ]
  },
  {
   "title": "hardware health",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(purefb_hw_status{job=~\"$job\",instance=~\"$instance\"} == 0)"
    }
   ]
  },
  {
   "title": "capacity usage distribution",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n  purefa_space_used_bytes{job=~\"$job\",instance=\"$instance\"}\n) by (dimension)",
     "legendFormat": "{{ dimension }}"
    },
    {
     "expr": "sum(purefa_space_capacity_bytes{job=~\"$job\",instance=\"$instance\"})\n-\nsum(\n  purefa_space_used_bytes{job=~\"$job\",instance=\"$instance\"}\n)",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "data reduction ratio",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(purefb_space_data_reduction{job=~\"$job\",instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "4 week capacity delta",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n  delta(\n    purefb_space_tot_physical_bytes{job=~\"$job\",instance=\"$instance\"}[4w]\n  )\n)"
    }
   ]
  },
  {
   "title": "io ratio",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 7, "y": 5 },
   "targets": [
    {
     "expr": "sum(purefb_perf_wr_ops{job=~\"$job\",instance=~\"$instance\"})\n/\nsum(purefb_perf_wr_ops{job=~\"$job\",instance=~\"$instance\"} + purefb_perf_rd_ops{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "write"
    },
    {
     "expr": "sum(purefb_perf_rd_ops{job=~\"$job\",instance=~\"$instance\"})\n/\nsum(purefb_perf_wr_ops{job=~\"$job\",instance=~\"$instance\"} + purefb_perf_rd_ops{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "read"
    }
   ]
  },
  { "title": "array performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "array iops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(\n  purefb_perf_rd_ops{job=~\"$job\",instance=\"$instance\"}\n)",
     "legendFormat": "read "
    },
    {
     "expr": "sum(\n  purefb_perf_wr_ops{job=~\"$job\",instance=\"$instance\"}\n)",
     "legendFormat": "write "
    }
   ]
  },
  {
   "title": "array latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(\n  purefb_perf_rd_latency_usec{job=~\"$job\",instance=\"$instance\"}\n) / 1000",
     "legendFormat": "read "
    },
    {
     "expr": "sum(\n  purefb_perf_wr_latency_usec{job=~\"$job\",instance=\"$instance\"}\n) / 1000",
     "legendFormat": "write "
    }
   ]
  },
  {
   "title": "array throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(\n  purefb_perf_rd_bps{job=~\"$job\",instance=\"$instance\"}\n)",
     "legendFormat": "read "
    },
    {
     "expr": "sum(\n  purefb_perf_wr_bps{job=~\"$job\",instance=\"$instance\"}\n)",
     "legendFormat": "write "
    }
   ]
  },
  { "title": "top talker volumes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "top talker volumes by iops",
   "type": "table",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(\n  purefa_volume_iops{job=~\"$job\",instance=\"$instance\",volume!~\"CV_.*\"}\n) by (volume)",
     "legendFormat": "{{ volume }}"
    }
   ]
  },
  {
   "title": "top talker volumes by latency",
   "type": "table",
   "gridPos": { "h": 15, "w": 8, "x": 8, "y": 33 },
   "targets": [
    {
     "expr": "avg(\n  purefa_volume_latency_usec{job=~\"$job\",instance=\"$instance\",volume!~\"CV_.*\"}\n) by (volume) / 1000",
     "legendFormat": "{{ volume }}"
    }
   ]
  },
  {
   "title": "top talker volumes by throughput",
   "type": "table",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 33 },
   "targets": [
    {
     "expr": "sum(\n  purefa_volume_throughput_bytes{job=~\"$job\",instance=\"$instance\",volume!~\"CV_.*\"}\n) by (volume)",
     "legendFormat": "{{ volume }}"
    }
   ]
  }
 ]
}