{
 "title": "Pure Storage FlashArray system hardware health",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": "label_values(purefa_info, job)" },
   {
    "name": "instance",
    "label": "FlashArray",
    "query": "label_values(purefa_info{job=\"$job\"}, instance)"
   },
   {
    "name": "controller",
    "label": "Controller",
    "query": "label_values(purefa_hardware_controller_health{instance=~\"$instance\"},controller)"
   }
  ]
 },
 "panels": [
  {
   "title": "array name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "purefa_info{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{ array_name }}"
    }
   ]
  },
  {
   "title": "firmware version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "purefa_info{job=~\"$job\",instance=\"$instance\"}",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "system events",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 5, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(purefa_alerts_total{job=~\"$job\",instance=~\"$instance\"}) by(severity)",
     "legendFormat": "{{ severity }}"
    }
   ]
  },
  {
   "title": "average temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(purefa_hardware_temperature_celsius{job=~\"$job\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "capacity usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefa_array_space_used_bytes{job=~\"$job\",instance=~\"$instance\"})\n/\nsum(purefa_array_space_capacity_bytes{job=~\"$job\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "average iops",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefa_array_performance_iops{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "{{ dimension }}"
    }
   ]
  },
  {
   "title": "average IO latency",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 19, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(purefa_array_performance_latency_usec{job=~\"$job\",instance=~\"$instance\"}) / 1000"
    }
   ]
  },
  {
   "title": "location",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "purefa_info{job=~\"$job\",instance=\"$instance\"}",
     "legendFormat": "{{ site}}"
    }
   ]
  },
  {
   "title": "average power voltage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(purefa_hardware_power_volts{job=~\"$job\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "data reduction",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(purefa_array_space_datareduction_ratio{job=~\"$job\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "average throughput",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefa_array_performance_throughput_bytes{job=~\"$job\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "chassis health",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "purefa_hardware_chassis_health{job=\"$job\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "disk bays",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(purefa_hardware_component_health{job=\"$job\",instance=\"$instance\",component=\"BAY\"})\n-\nsum(purefa_hardware_component_health{job=\"$job\",instance=\"$instance\",component=\"BAY\"})"
    }
   ]
  },
  {
   "title": "failed SSDs",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 4, "x": 11, "y": 6 },
   "targets": [
    {
     "expr": "purefa_hardware_component_health{job=~\"$job\",instance=~\"$instance\",component=\"BAY\"} != 1",
     "legendFormat": "disk bay {{ index }}"
    }
   ]
  },
  {
   "title": "failed NVRAM modules",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 6 },
   "targets": [
    {
     "expr": "purefa_hardware_component_health{job=~\"$job\",instance=~\"$instance\",component=\"NVB\"} == 0",
     "legendFormat": "NVRAM {{ index }}"
    }
   ]
  },
  {
   "title": "failed power supplies",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 4, "x": 19, "y": 6 },
   "targets": [
    {
     "expr": "purefa_hardware_component_health{job=~\"$job\",instance=~\"$instance\",component=\"PWR\"} != 1",
     "legendFormat": "power supply {{ index }}"
    }
   ]
  },
  {
   "title": "NVRAM",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(purefa_hardware_component_health{job=\"$job\",instance=\"$instance\",component=\"NVB\"})\n-\nsum(purefa_hardware_component_health{job=\"$job\",instance=\"$instance\",component=\"NVB\"})"
    }
   ]
  },
  {
   "title": "power supply",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(purefa_hardware_component_health{job=\"$job\",instance=\"$instance\",component=\"PWR\"})\n-\nsum(purefa_hardware_component_health{job=\"$job\",instance=\"$instance\",component=\"PWR\"})"
    }
   ]
  },
  { "title": "controller $controller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }, "repeat": "controller" },
  {
   "title": "controller health",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "purefa_hardware_controller_health{job=\"$job\",instance=\"$instance\",controller=~\"$controller\"}"
    }
   ]
  },
  {
   "title": "ethernet ports",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(purefa_hardware_component_health{job=\"$job\",instance=\"$instance\",controller=~\"$controller\",component=\"ETH\"})\n-\nsum(purefa_hardware_component_health{job=\"$job\",instance=\"$instance\",controller=~\"$controller\",component=\"ETH\"})"
    }
   ]
  },
  {
   "title": "failed ethernet ports",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 4, "x": 7, "y": 13 },
   "targets": [
    {
     "expr": "purefa_hardware_component_health{job=~\"$job\",instance=~\"$instance\",component=\"ETH\",controller=~\"$controller\"} == 0",
     "legendFormat": "ethernet {{ index }}"
    }
   ]
  },
  {
   "title": "failed fibre channel ports",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 4, "x": 11, "y": 13 },
   "targets": [
    {
     "expr": "purefa_hardware_component_health{job=~\"$job\",instance=~\"$instance\",component=\"FC\",controller=~\"$controller\"} == 0",
     "legendFormat": "fibre channel port {{ index }}"
    }
   ]
  },
  {
   "title": "failed fans",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 4, "x": 15, "y": 13 },
   "targets": [
    {
     "expr": "purefa_hardware_component_health{job=~\"$job\",instance=~\"$instance\",component=\"FAN\",controller=~\"$controller\"} == 0",
     "legendFormat": "fan {{ index }}"
    }
   ]
  },
  {
   "title": "failed temperature sensors",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 4, "x": 19, "y": 13 },
   "targets": [
    {
     "expr": "purefa_hardware_component_health{job=~\"$job\",instance=~\"$instance\",component=\"TMP\",controller=~\"$controller\"} == 0",
     "legendFormat": "sensor {{ index }}"
    }
   ]
  },
  {
   "title": "fibre channel ports",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 3, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(purefa_hardware_component_health{job=\"$job\",instance=\"$instance\",controller=~\"$controller\",component=\"FC\"})\n-\nsum(purefa_hardware_component_health{job=\"$job\",instance=\"$instance\",controller=~\"$controller\",component=\"FC\"})"
    }
   ]
  },
  {
   "title": "fans",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(purefa_hardware_component_health{job=\"$job\",instance=\"$instance\",controller=~\"$controller\",component=\"FAN\"})\n-\nsum(purefa_hardware_component_health{job=\"$job\",instance=\"$instance\",controller=~\"$controller\",component=\"FAN\"})"
    }
   ]
  },
  {
   "title": "average temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(purefa_hardware_temperature_celsius{job=~\"$job\",instance=~\"$instance\",controller=~\"$controller\"})"
    }
   ]
  },
  {
   "title": "temperature sensors",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 3, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(purefa_hardware_component_health{job=\"$job\",instance=\"$instance\",controller=~\"$controller\",component=\"TMP\"})\n-\nsum(purefa_hardware_component_health{job=\"$job\",instance=\"$instance\",controller=~\"$controller\",component=\"TMP\"})"
    }
   ]
  }
 ]
}