{
 "title": "Pure Storage FlashBlade storage usage detail",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": "label_values(purefb_info, job)" },
   {
    "name": "instance",
    "label": "FlashBlade",
    "query": "label_values(purefb_info{job=\"$job\"}, instance)"
   },
   { "name": "norm_percent", "label": "normalized Percent", "query": "60,70,80,90" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<center>\n  <h1>Pure Storage FlashBlade storage usage</h1>\n</center>"
  },
  {
   "title": "array name",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "purefb_info{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{ array_name }}"
    }
   ]
  },
  {
   "title": "Free space",
   "type": "stat",
   "description": "Physical free space (native)",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefb_array_capacity_bytes{job=~\"$job\",instance=~\"$instance\"})\n-\nsum(purefb_array_space_bytes{job=~\"$job\",instance=~\"$instance\",dimension=\"total_physical\"})"
    }
   ]
  },
  {
   "title": "capacity usage distribution",
   "type": "graph",
   "gridPos": { "h": 9, "w": 14, "x": 6, "y": 2 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(purefb_array_space_bytes{job=~\"$job\",instance=~\"$instance\"}) by (dimension)",
     "legendFormat": "{{ dimension }}"
    },
    {
     "expr": "sum(purefb_array_capacity_bytes{job=~\"$job\",instance=~\"$instance\"})\n-\nsum(purefb_array_space_bytes{job=~\"$job\",instance=~\"$instance\",dimension=\"total_physical\"})",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "capacity usage on array",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefb_array_space_bytes{job=\"$job\", instance=~\"$instance\", dimension=\"total_physical\"})"
    }
   ]
  },
  {
   "title": "array capacity usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefb_array_space_bytes{job=~\"$job\",instance=~\"$instance\",dimension=\"total_physical\"})\n/\nsum(purefb_array_capacity_bytes{job=~\"$job\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Free based on $norm_percent  % full",
   "type": "stat",
   "description": "Physical free space normalized $norm_percent %\n\npysical_free_space  * normalized_percent / 100 ",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(purefb_array_capacity_bytes{job=~\"$job\",instance=~\"$instance\"}) * $norm_percent /100)\n-\nsum(purefb_array_space_bytes{job=~\"$job\",instance=~\"$instance\",dimension=\"total_physical\"})"
    }
   ]
  },
  {
   "title": "Provisioned on Array",
   "type": "stat",
   "description": "Provisioned space.",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "purefb_array_capacity_bytes{job=\"$job\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "data reduction ratio",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(purefb_array_space_data_reduction{job=~\"$job\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Free usable",
   "type": "stat",
   "description": "logical free Space normalized.  \n(physical_free_space  * normalized_percent\n/ 100\n) *  data_reduction",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((sum(purefb_array_capacity_bytes{job=~\"$job\",instance=~\"$instance\"}) * $norm_percent /100)\n-\nsum(purefb_array_space_bytes{job=~\"$job\",instance=~\"$instance\",dimension=\"total_physical\"})) \n* \navg(purefb_array_space_data_reduction{job=~\"$job\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "4 week capacity delta",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(\n  delta(\n    purefb_array_space_bytes{job=~\"$job\",instance=~\"$instance\",dimension=\"total_physical\"}[4w]\n  )\n)"
    }
   ]
  },
  {
   "title": "file systems space usage",
   "type": "table-old",
   "gridPos": { "h": 16, "w": 7, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(purefb_filesystems_space_bytes{job=~\"$job\",instance=\"$instance\",dimension=\"total_physical\"}\n) by (name)",
     "legendFormat": "{{ name}}"
    }
   ]
  },
  {
   "title": "file systems size",
   "type": "table-old",
   "gridPos": { "h": 16, "w": 9, "x": 7, "y": 11 },
   "targets": [
    {
     "expr": "sum(purefb_filesystems_space_bytes{job=~\"$job\",instance=~\"$instance\",dimension=\"virtual\"}\n) by (name)",
     "legendFormat": "{{ name}}"
    }
   ]
  },
  {
   "title": "file systems data reduction ratio",
   "type": "table-old",
   "gridPos": { "h": 16, "w": 8, "x": 16, "y": 11 },
   "targets": [
    {
     "expr": "sum(\n  purefb_filesystems_data_reduction{job=~\"$job\",instance=~\"$instance\"}\n) by (name)",
     "legendFormat": "{{ name}}"
    }
   ]
  }
 ]
}