{
 "title": "Pure Storage FlashBlade system detail",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": "label_values(purefb_info, job)" },
   {
    "name": "instance",
    "label": "FlashBlade",
    "query": "label_values(purefb_info{job=\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "array name",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "purefb_info{job=~\"$job\",instance=\"$instance\"}",
     "legendFormat": "{{ array_name }}"
    }
   ]
  },
  {
   "title": "firmware",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "purefb_info{job=~\"$job\",instance=\"$instance\"}",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "system events",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(purefb_open_events_total{job=~\"$job\",instance=~\"$instance\"}) by(severity)",
     "legendFormat": "{{ severity }}"
    }
   ]
  },
  {
   "title": "array capacity usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefb_array_space_bytes{job=~\"$job\",instance=\"$instance\",dimension=\"total_physical\"})\n/\nsum(purefb_array_capacity_bytes{job=~\"$job\",instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "average iops",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefb_array_performance_iops{job=~\"$job\",instance=\"$instance\"})",
     "legendFormat": "{{ dimension }}"
    }
   ]
  },
  {
   "title": "average latency",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefb_array_performance_latency_usec{job=~\"$job\",instance=\"$instance\"}) / 1000"
    }
   ]
  },
  {
   "title": "average throughput",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefb_array_performance_throughput_bytes{job=~\"$job\",instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "hardware health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(purefb_hw_status{job=~\"$job\",instance=~\"$instance\"} == 0)"
    }
   ]
  },
  {
   "title": "capacity usage distribution",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n  purefb_array_space_bytes{job=~\"$job\",instance=\"$instance\"}\n) by (dimension)",
     "legendFormat": "{{ dimension }}"
    },
    {
     "expr": "sum(purefa_space_capacity_bytes{job=~\"$job\",instance=\"$instance\"})\n-\nsum(\n  purefa_space_used_bytes{job=~\"$job\",instance=\"$instance\"}\n)",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "data reduction ratio",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefb_array_space_data_reduction{job=~\"$job\",instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "4 week capacity delta",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(\n  delta(\n    purefb_array_space_bytes{job=~\"$job\",instance=\"$instance\",dimension=\"total_physical\"}[4w]\n  )\n)"
    }
   ]
  },
  {
   "title": "io ratio",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefb_array_performance_iops{job=~\"$job\",instance=~\"$instance\",dimension=\"write\"})\n/\nsum(purefb_array_performance_iops{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "write"
    },
    {
     "expr": "sum(purefb_array_performance_iops{job=~\"$job\",instance=~\"$instance\",dimension=\"read\"})\n/\nsum(purefb_array_performance_iops{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "read"
    },
    {
     "expr": "sum(purefb_array_performance_iops{job=~\"$job\",instance=~\"$instance\",dimension=\"other\"})\n/\nsum(purefb_array_performance_iops{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "other"
    }
   ]
  },
  { "title": "array performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "array iops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(purefb_array_performance_iops{job=~\"$job\",instance=\"$instance\",dimension=\"read\"})",
     "legendFormat": "read "
    },
    {
     "expr": "sum(purefb_array_performance_iops{job=~\"$job\",instance=\"$instance\",dimension=\"write\"})",
     "legendFormat": "write "
    },
    {
     "expr": "sum(purefb_array_performance_iops{job=~\"$job\",instance=\"$instance\",dimension=\"other\"})",
     "legendFormat": "other"
    }
   ]
  },
  {
   "title": "array latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(purefb_array_performance_latency_usec{job=~\"$job\",instance=\"$instance\",dimension=\"read\"}) / 1000",
     "legendFormat": "read "
    },
    {
     "expr": "sum(purefb_array_performance_latency_usec{job=~\"$job\",instance=\"$instance\",dimension=\"write\"}) / 1000",
     "legendFormat": "write "
    },
    {
     "expr": "sum(purefb_array_performance_latency_usec{job=~\"$job\",instance=\"$instance\",dimension=\"other\"}) / 1000",
     "legendFormat": "other"
    }
   ]
  },
  {
   "title": "array throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(purefb_array_performance_throughput_bytes{job=~\"$job\",instance=\"$instance\",dimension=\"read\"})",
     "legendFormat": "read "
    },
    {
     "expr": "sum(purefb_array_performance_throughput_bytes{job=~\"$job\",instance=\"$instance\",dimension=\"write\"})",
     "legendFormat": "write "
    }
   ]
  },
  { "title": "top talker volumes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "top talker file systems by iops",
   "type": "table-old",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(\n  purefb_filesystem_performance_iops{job=~\"$job\",instance=\"$instance\"}\n) by (name)",
     "legendFormat": "{{ name}}"
    }
   ]
  },
  {
   "title": "top talker filesystems by latency",
   "type": "table-old",
   "gridPos": { "h": 15, "w": 8, "x": 8, "y": 33 },
   "targets": [
    {
     "expr": "avg(\n  purefb_filesystem_performance_latency_usec{job=~\"$job\",instance=\"$instance\"}\n) by (name) / 1000",
     "legendFormat": "{{ volume }}"
    }
   ]
  },
  {
   "title": "top talker file systems by throughput",
   "type": "table-old",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 33 },
   "targets": [
    {
     "expr": "sum(\n  purefb_filesystem_performance_throughput_bytes{job=~\"$job\",instance=\"$instance\"}\n) by (name)",
     "legendFormat": "{{ volume }}"
    }
   ]
  }
 ]
}