{
 "title": "Pure Storage FlashArray volume detail",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": "label_values(purefa_info, job)" },
   {
    "name": "instance",
    "label": "FlashArray",
    "query": "label_values(purefa_info{job=\"$job\"}, instance)"
   },
   {
    "name": "volume",
    "label": "Volume",
    "query": "label_values(purefa_volume_size_bytes{job=\"$job\",instance=\"$instance\"}, volume)"
   }
  ]
 },
 "panels": [
  {
   "title": "array name",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "purefa_info{job=~\"$job\",instance=\"$instance\"}",
     "legendFormat": "{{ array_name }}"
    }
   ]
  },
  {
   "title": "capacity usage distribution",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n  purefa_volume_space_bytes{job=~\"$job\",instance=~\"$instance\",volume=\"$volume\"}\n) by (dimension)",
     "legendFormat": "{{ dimension }}"
    },
    {
     "expr": "sum(\n  purefa_volume_size_bytes{job=~\"$job\",instance=~\"$instance\",volume=\"$volume\"}\n)\n-\nsum(\n  purefa_volume_space_bytes{job=~\"$job\",instance=~\"$instance\",volume=\"$volume\"}\n)",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "average volume iops",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 13, "y": 0 },
   "format": "iops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(purefa_volume_iops{job=~\"$job\",instance=\"$instance\",volume=\"$volume\"})"
    }
   ]
  },
  {
   "title": "data reduction ratio",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(purefa_volume_datareduction_ratio{job=~\"$job\",instance=\"$instance\",volume=\"$volume\"})"
    }
   ]
  },
  {
   "title": "volume capacity usage",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 2 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(purefa_volume_space_bytes{job=~\"$job\",instance=~\"$instance\",volume=\"$volume\"})\n/\nsum(purefa_volume_size_bytes{job=~\"$job\",instance=~\"$instance\",volume=\"$volume\"})"
    }
   ]
  },
  {
   "title": "average volume latency",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 13, "y": 2 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(\n  purefa_volume_latency_usec{job=~\"$job\",instance=\"$instance\",volume=\"$volume\"}\n) / 1000"
    }
   ]
  },
  {
   "title": "iops read ratio",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(purefa_volume_iops{job=~\"$job\",instance=~\"$instance\",volume=\"$volume\",dimension=\"read\"})\n/\nsum(purefa_volume_iops{job=~\"$job\",instance=~\"$instance\",volume=\"$volume\"})"
    }
   ]
  },
  {
   "title": "iops write ratio",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(purefa_volume_iops{job=~\"$job\",instance=~\"$instance\",volume=\"$volume\",dimension=\"write\"})\n/\nsum(purefa_volume_iops{job=~\"$job\",instance=~\"$instance\",volume=\"$volume\"})"
    }
   ]
  },
  {
   "title": "volume capacity",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "purefa_volume_size_bytes{job=~\"$job\",instance=~\"$instance\",volume=\"$volume\"}"
    }
   ]
  },
  {
   "title": "average volume throughput",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 13, "y": 4 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(\n  purefa_volume_throughput_bytes{job=~\"$job\",instance=\"$instance\",volume=\"$volume\"}\n)"
    }
   ]
  },
  {
   "title": "volume iops",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(\n  purefa_volume_iops{job=~\"$job\",instance=\"$instance\",volume=\"$volume\",dimension=\"read\"}\n)",
     "legendFormat": "{{ volume}} read "
    },
    {
     "expr": "sum(\n  purefa_volume_iops{job=~\"$job\",instance=\"$instance\",volume=\"$volume\",dimension=\"write\"}\n)",
     "legendFormat": "{{ volume}} write "
    }
   ]
  },
  {
   "title": "volume latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(\n  purefa_volume_latency_usec{job=~\"$job\",instance=\"$instance\",volume=\"$volume\",dimension=\"read\"}\n) / 1000",
     "legendFormat": "{{ volume}} read "
    },
    {
     "expr": "sum(\n  purefa_volume_latency_usec{job=~\"$job\",instance=\"$instance\",volume=\"$volume\",dimension=\"write\"}\n) / 1000",
     "legendFormat": "{{ volume}} write "
    }
   ]
  },
  {
   "title": "volume throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(\n  purefa_volume_throughput_bytes{job=~\"$job\",instance=\"$instance\",volume=\"$volume\",dimension=\"read\"}\n)",
     "legendFormat": "{{ volume}} read "
    },
    {
     "expr": "sum(\n  purefa_volume_throughput_bytes{job=~\"$job\",instance=\"$instance\",volume=\"$volume\",dimension=\"write\"}\n)",
     "legendFormat": "{{ volume}} write "
    }
   ]
  }
 ]
}