{
 "title": "Pure Storage FlashArray volume detail",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": "label_values(purefa_info, job)" },
   {
    "name": "instance",
    "label": "FlashArray",
    "query": "label_values(purefa_info{job=\"$job\"}, instance)"
   },
   {
    "name": "volume",
    "label": "Volume",
    "query": "label_values(purefa_volume_space_size_bytes{job=\"$job\",instance=\"$instance\"}, volume)"
   }
  ]
 },
 "panels": [
  {
   "title": "array name",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "purefa_info{job=~\"$job\",instance=\"$instance\"}",
     "legendFormat": "{{ array_name }}"
    }
   ]
  },
  {
   "title": "capacity usage distribution",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n  purefa_volume_space_bytes{job=~\"$job\",instance=~\"$instance\",volume=\"$volume\"}\n) by (dimension)",
     "legendFormat": "{{ dimension }}"
    },
    {
     "expr": "sum(purefa_volume_size_bytes{job=~\"$job\",instance=~\"$instance\",volume=\"$volume\"})\n-\nsum(purefa_volume_space_bytes{job=~\"$job\",instance=~\"$instance\",volume=\"$volume\"})",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "average volume iops",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefa_volume_performance_iops{job=~\"$job\",instance=\"$instance\",volume=\"$volume\"})"
    }
   ]
  },
  {
   "title": "iops ratio",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefa_volume_performance_iops{job=~\"$job\",instance=~\"$instance\",volume=\"$volume\",dimension=\"read\"})\n/\nsum(purefa_volume_performance_iops{job=~\"$job\",instance=~\"$instance\",volume=\"$volume\"})",
     "legendFormat": "read"
    },
    {
     "expr": "sum(purefa_volume_performance_iops{job=~\"$job\",instance=~\"$instance\",volume=\"$volume\",dimension=\"write\"})\n/\nsum(purefa_volume_performance_iops{job=~\"$job\",instance=~\"$instance\",volume=\"$volume\"})",
     "legendFormat": "write"
    },
    {
     "expr": "sum(purefa_volume_performance_iops{job=~\"$job\",instance=~\"$instance\",volume=\"$volume\",dimension=\"mirrored_write\"})\n/\nsum(purefa_volume_performance_iops{job=~\"$job\",instance=~\"$instance\",volume=\"$volume\"})",
     "legendFormat": "mirrored write"
    }
   ]
  },
  {
   "title": "data reduction ratio",
   "type": "michaeldmoore-annunciator-panel",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(purefa_volume_space_datareduction_ratio{job=~\"$job\",instance=\"$instance\",volume=\"$volume\"})"
    }
   ]
  },
  {
   "title": "volume capacity usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefa_volume_space_bytes{job=~\"$job\",instance=~\"$instance\",volume=\"$volume\"})\n/\nsum(purefa_volume_space_size_bytes{job=~\"$job\",instance=~\"$instance\",volume=\"$volume\"})"
    }
   ]
  },
  {
   "title": "average volume latency",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 13, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(\n  purefa_volume_performance_latency_usec{job=~\"$job\",instance=\"$instance\",volume=\"$volume\"}\n) / 1000"
    }
   ]
  },
  {
   "title": "volume capacity",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "purefa_volume_space_size_bytes{job=~\"$job\",instance=~\"$instance\",volume=\"$volume\"}"
    }
   ]
  },
  {
   "title": "average volume throughput",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(\n  purefa_volume_performance_throughput_bytes{job=~\"$job\",instance=\"$instance\",volume=\"$volume\"}\n)"
    }
   ]
  },
  {
   "title": "volume iops",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(\n  purefa_volume_performance_iops{job=~\"$job\",instance=\"$instance\",volume=\"$volume\",dimension=\"read\"}\n)",
     "legendFormat": "{{ volume}} read "
    },
    {
     "expr": "sum(\n  purefa_volume_performance_iops{job=~\"$job\",instance=\"$instance\",volume=\"$volume\",dimension=\"write\"}\n)",
     "legendFormat": "{{ volume}} write "
    }
   ]
  },
  {
   "title": "volume latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(\n  purefa_volume_performance_latency_usec{job=~\"$job\",instance=\"$instance\",volume=\"$volume\",dimension=\"read\"}\n) / 1000",
     "legendFormat": "{{ volume}} read "
    },
    {
     "expr": "sum(\n  purefa_volume_performance_latency_usec{job=~\"$job\",instance=\"$instance\",volume=\"$volume\",dimension=\"write\"}\n) / 1000",
     "legendFormat": "{{ volume}} write "
    }
   ]
  },
  {
   "title": "volume throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(\n  purefa_volume_performance_throughput_bytes{job=~\"$job\",instance=\"$instance\",volume=\"$volume\",dimension=\"read\"}\n)",
     "legendFormat": "{{ volume}} read "
    },
    {
     "expr": "sum(\n  purefa_volume_performance_throughput_bytes{job=~\"$job\",instance=\"$instance\",volume=\"$volume\",dimension=\"write\"}\n)",
     "legendFormat": "{{ volume}} write "
    }
   ]
  }
 ]
}