{
 "title": "Pure Storage FlashArray storage usage",
 "time": { "from": "now-90d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": "label_values(purefa_info, job)" },
   {
    "name": "instance",
    "label": "FlashArray",
    "query": "label_values(purefa_info{job=\"$job\"}, instance)"
   },
   { "name": "norm_percent", "label": "normalized Percent", "query": "60,70,80,90" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<center>\n  <h1>Pure Storage FlashArray storage usage</h1>\n</center>"
  },
  {
   "title": "array name",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "purefa_info{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{ array_name }}"
    }
   ]
  },
  {
   "title": "Free space",
   "type": "stat",
   "description": "Physical free space (native)",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefa_array_space_capacity_bytes{job=~\"$job\",instance=~\"$instance\"})\n-\nsum(purefa_array_space_used_bytes{job=~\"$job\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "capacity usage distribution",
   "type": "graph",
   "gridPos": { "h": 9, "w": 14, "x": 6, "y": 2 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(purefa_array_space_used_bytes{job=~\"$job\",instance=~\"$instance\"}) by (dimension)",
     "legendFormat": "{{ dimension }}"
    },
    {
     "expr": "sum(purefa_array_space_capacity_bytes{job=~\"$job\",instance=~\"$instance\"})\n-\nsum(purefa_array_space_used_bytes{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "capacity usage on array",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefa_array_space_used_bytes{job=\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "array capacity usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefa_array_space_used_bytes{job=~\"$job\",instance=~\"$instance\"})\n/\nsum(purefa_array_space_capacity_bytes{job=~\"$job\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Free based on $norm_percent  % full",
   "type": "stat",
   "description": "Physical free space normalized $norm_percent %\n\npysical_free_space  * normalized_percent / 100 ",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(purefa_array_space_capacity_bytes{job=~\"$job\",instance=~\"$instance\"}) * $norm_percent /100)\n-\nsum(purefa_array_space_used_bytes{job=~\"$job\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Provisioned on Array",
   "type": "stat",
   "description": "Provisioned volume space.",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "purefa_array_space_provisioned_bytes{job=\"$job\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "data reduction ratio",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(purefa_array_space_datareduction_ratio{job=~\"$job\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Over provioning based on array",
   "type": "stat",
   "description": "Over provisioning in percent.......\nphysical_space / provision_volume_space",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefa_array_space_provisioned_bytes{job=\"$job\", instance=\"$instance\"}) / sum(purefa_array_space_capacity_bytes{job=\"$job\", instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Free usable",
   "type": "stat",
   "description": "logical free Space normalized.  \n(physical_free_space  * normalized_percent\n/ 100\n) *  data_reduction",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((sum(purefa_array_space_capacity_bytes{job=~\"$job\",instance=~\"$instance\"}) * $norm_percent /100)\n-\nsum(purefa_array_space_used_bytes{job=~\"$job\",instance=~\"$instance\"})) \n* \navg(purefa_array_space_datareduction_ratio{job=~\"$job\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Free base on array op",
   "type": "stat",
   "description": "Storage you can provision base on over provisioning ...............................................\n(physical_free_space  * normalized_percent\n/ 100\n) * over_provisioning_percent",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((sum(purefa_array_space_capacity_bytes{job=~\"$job\", instance=~\"$instance\"}) * $norm_percent /100)\n-\nsum(purefa_array_space_used_bytes{job=~\"$job\", instance=~\"$instance\"})) \n* \n(sum(purefa_array_space_provisioned_bytes{job=\"$job\", instance=~\"$instance\"}) / sum(purefa_array_space_capacity_bytes{job=\"$job\", instance=~\"$instance\"}))"
    }
   ]
  },
  {
   "title": "4 week capacity delta",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(delta(purefa_array_space_used_bytes{job=~\"$job\",instance=~\"$instance\"}[4w]))"
    }
   ]
  },
  {
   "title": "volumes space usage",
   "type": "table-old",
   "gridPos": { "h": 16, "w": 7, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(\n  purefa_volume_space_bytes{job=\"$job\",instance=\"$instance\"}\n) by (volume)",
     "legendFormat": "{{ volume }}"
    }
   ]
  },
  {
   "title": "volumes size",
   "type": "table-old",
   "gridPos": { "h": 16, "w": 9, "x": 7, "y": 11 },
   "targets": [
    {
     "expr": "sum(\n  purefa_volume_space_size_bytes{job=~\"$job\",instance=~\"$instance\"}\n) by (volume)",
     "legendFormat": "{{ volume }}"
    }
   ]
  },
  {
   "title": "volumes data reduction ratio",
   "type": "table-old",
   "gridPos": { "h": 16, "w": 8, "x": 16, "y": 11 },
   "targets": [
    {
     "expr": "sum(\n  purefa_volume_datareduction_ratio{job=~\"$job\",instance=~\"$instance\",volume!~\"CV_.*\"}\n) by (volume)",
     "legendFormat": "{{ volume }}"
    }
   ]
  }
 ]
}