IMAGE_NAMESPACE = quay.io/purestorage
IMAGE_NAME = pure-fa-exporter
IMAGE_TAG ?= latest
EXPORTER ?= pure_fa_exporter
REQUIREMENTS = requirements.fa.txt
DOCKERFILE ?= Dockerfile.fa
RUN_PORT ?= 9491
TEST_PORT ?= 8123
TIMEO ?= 30
WORKERS ?= 2

default: build

.PHONY: build
build:
        make IMAGE_NAMESPACE=$(IMAGE_NAMESPACE) IMAGE_NAME=$(IMAGE_NAME) \
                IMAGE_TAG=$(IMAGE_TAG) REQUIREMENTS=$(REQUIREMENTS) DOCKERFILE=$(DOCKERFILE) \
                RUN_PORT=$(RUN_PORT) TIMEO=$(TIMEO) WORKERS=$(WORKERS) EXPORTER=$(EXPORTER) -f Makefile.mk

.PHONY: test
test:
        make IMAGE_NAMESPACE=$(IMAGE_NAMESPACE) IMAGE_NAME=$(IMAGE_NAME) \
                IMAGE_TAG=$(IMAGE_TAG) REQUIREMENTS=$(REQUIREMENTS) DOCKERFILE=$(DOCKERFILE) \
                RUN_PORT=$(RUN_PORT) TIMEO=$(TIMEO) WORKERS=$(WORKERS) EXPORTER=$(EXPORTER) -f Makefile.mk test

.PHONY: test-docker
test-docker: build
        make IMAGE_NAMESPACE=$(IMAGE_NAMESPACE) IMAGE_NAME=$(IMAGE_NAME) \
                IMAGE_TAG=$(IMAGE_TAG) REQUIREMENTS=$(REQUIREMENTS) DOCKERFILE=$(DOCKERFILE) \
                RUN_PORT=$(RUN_PORT) TIMEO=$(TIMEO) WORKERS=$(WORKERS) -f Makefile.mk test-docker
